# Generated by Django 3.1.7 on 2021-03-31 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=50)),
                ('Event_Description', models.TextField()),
                ('Event_Start_Date', models.DateTimeField()),
                ('Event_End_Date', models.DateTimeField()),
                ('Event_Mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH OFFLINE AND ONLINE', 'Both Offline and Onine')], default='Online', max_length=40)),
                ('Event_Organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubEvent_Name', models.CharField(max_length=50)),
                ('SubEvent_Description', models.TextField()),
                ('SubEvent_Start_Date', models.DateTimeField()),
                ('SubEvent_End_Date', models.DateTimeField()),
                ('SubEvent_Mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH OFFLINE AND ONLINE', 'Both Offline and Onine')], default='Online', max_length=40)),
                ('SubEvent_Reg_Fees', models.IntegerField()),
                ('SubEvent_Participation', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], max_length=100)),
                ('SubEvent_Note', models.CharField(default=None, max_length=50)),
                ('SubEvent_Type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('NON-TECHNICAL', 'Non-Technical')], max_length=20)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.event')),
            ],
        ),
    ]
