# Generated by Django 3.1.7 on 2021-04-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subevent',
            old_name='Event',
            new_name='Event_id',
        ),
    ]
