# Generated by Django 3.1.7 on 2021-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210404_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_Category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('NON-TECHNICAL', 'Non-Technical')], default='Technical', max_length=100),
        ),
    ]
